version: "3.8"

services:
  gateway:
    container_name: fanteract-gateway
    image: fanteract-gateway:latest
    ports:
      - "8000:8000"
    environment:
      EUREKA_INSTANCE_IP_ADDRESS: ${PRIVATE_IP}
      SPRING_PROFILES_ACTIVE: prod
    restart: always